[package]
name = "remotebarcode"
version = "0.1.0"
authors = ["Menno Vossen <nemno@kuopzi.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keybd_event = "0.1.2"
iron = "0.6.1"
persistent = "0.4.0"
